#!/usr/bin/env perl

use strict;
use warnings;

use lib 'lib';
use lib '/home/mig29/TwitNews/lib/';

# Start command line interface for application
require Mojolicious::Commands;
Mojolicious::Commands->start_app('TwitNews');
